// Measured from Apple's iOS 27 UI kit renderings. Generated by
// scripts/build_design_tokens.py -- do not hand-edit.
//
// On Apple platforms, prefer the semantic APIs (Color.accentColor,
// UIColor.systemBlue, .primary) over these literals: they adapt to
// Dark Mode and Increase Contrast on their own, and they track
// whatever Apple changes next. Reach for these values only where the
// semantic API can't -- custom drawing, a canvas, or matching Apple's
// palette on a platform that has none.

import SwiftUI

public enum AppleKitColor {
    /// light #0088FF · dark #0091FF
    public static let accent = Color(uiColor: UIColor { t in
        t.userInterfaceStyle == .dark
            ? UIColor(red: 0.000, green: 0.569, blue: 1.000, alpha: 1.000)
            : UIColor(red: 0.000, green: 0.533, blue: 1.000, alpha: 1.000)
    })
    /// light rgba(115, 115, 123, 0.122) · dark rgba(117, 117, 129, 0.239)
    public static let fillControl = Color(uiColor: UIColor { t in
        t.userInterfaceStyle == .dark
            ? UIColor(red: 0.459, green: 0.459, blue: 0.506, alpha: 0.239)
            : UIColor(red: 0.451, green: 0.451, blue: 0.482, alpha: 0.122)
    })
    /// light rgba(60, 60, 67, 0.298) · dark rgba(235, 235, 245, 0.298)
    public static let fillTrack = Color(uiColor: UIColor { t in
        t.userInterfaceStyle == .dark
            ? UIColor(red: 0.922, green: 0.922, blue: 0.961, alpha: 0.298)
            : UIColor(red: 0.235, green: 0.235, blue: 0.263, alpha: 0.298)
    })
    /// light #34C759 · dark #30D158
    public static let green = Color(uiColor: UIColor { t in
        t.userInterfaceStyle == .dark
            ? UIColor(red: 0.188, green: 0.820, blue: 0.345, alpha: 1.000)
            : UIColor(red: 0.204, green: 0.780, blue: 0.349, alpha: 1.000)
    })
    /// light #1A1A1A · dark #F5F5F5
    public static let label = Color(uiColor: UIColor { t in
        t.userInterfaceStyle == .dark
            ? UIColor(red: 0.961, green: 0.961, blue: 0.961, alpha: 1.000)
            : UIColor(red: 0.102, green: 0.102, blue: 0.102, alpha: 1.000)
    })
    /// light rgba(60, 60, 67, 0.6) · dark rgba(235, 235, 245, 0.698)
    public static let labelSecondary = Color(uiColor: UIColor { t in
        t.userInterfaceStyle == .dark
            ? UIColor(red: 0.922, green: 0.922, blue: 0.961, alpha: 0.698)
            : UIColor(red: 0.235, green: 0.235, blue: 0.263, alpha: 0.600)
    })
    /// light rgba(60, 60, 67, 0.298) · dark rgba(235, 235, 245, 0.298)
    public static let labelTertiary = Color(uiColor: UIColor { t in
        t.userInterfaceStyle == .dark
            ? UIColor(red: 0.922, green: 0.922, blue: 0.961, alpha: 0.298)
            : UIColor(red: 0.235, green: 0.235, blue: 0.263, alpha: 0.298)
    })
    /// light #FF383C · dark #FF4245
    public static let red = Color(uiColor: UIColor { t in
        t.userInterfaceStyle == .dark
            ? UIColor(red: 1.000, green: 0.259, blue: 0.271, alpha: 1.000)
            : UIColor(red: 1.000, green: 0.220, blue: 0.235, alpha: 1.000)
    })
    /// light #E6E6E6 · dark #1A1A1A
    public static let surface = Color(uiColor: UIColor { t in
        t.userInterfaceStyle == .dark
            ? UIColor(red: 0.102, green: 0.102, blue: 0.102, alpha: 1.000)
            : UIColor(red: 0.902, green: 0.902, blue: 0.902, alpha: 1.000)
    })
}

public enum AppleKitMetric {
    public static let stepperSize = CGSize(width: 46.0, height: 32.0)
    public static let stepperRadius: CGFloat = 16.0
    public static let switchSize = CGSize(width: 64.0, height: 28.0)
    public static let switchRadius: CGFloat = 13.7
    public static let tabPillSize = CGSize(width: 77.0, height: 36.0)
    public static let tabPillRadius: CGFloat = 17.9
    /// buttons.md states 44x44 pt as the general hit-region rule.
    public static let hitTarget: CGFloat = 44
}
