// Measured from Apple's iOS 27 UI kit renderings. Generated by
// scripts/build_design_tokens.py -- do not hand-edit.
//
// On Android, this is Apple's palette on a platform with its own.
// Material has its own colour roles and its own switch, and users
// expect them. Use these when brand consistency across platforms is
// the deliberate goal -- not by default.

import 'dart:ui';

class AppleKitLight {
  static const accent = Color(0xFF0088FF);
  static const fillControl = Color(0x1F73737B);
  static const fillTrack = Color(0x4C3C3C43);
  static const green = Color(0xFF34C759);
  static const label = Color(0xFF1A1A1A);
  static const labelSecondary = Color(0x993C3C43);
  static const labelTertiary = Color(0x4C3C3C43);
  static const red = Color(0xFFFF383C);
  static const surface = Color(0xFFE6E6E6);
}

class AppleKitDark {
  static const accent = Color(0xFF0091FF);
  static const fillControl = Color(0x3D757581);
  static const fillTrack = Color(0x4CEBEBF5);
  static const green = Color(0xFF30D158);
  static const label = Color(0xFFF5F5F5);
  static const labelSecondary = Color(0xB2EBEBF5);
  static const labelTertiary = Color(0x4CEBEBF5);
  static const red = Color(0xFFFF4245);
  static const surface = Color(0xFF1A1A1A);
}

class AppleKitMetric {
  static const stepperWidth = 46.0;
  static const stepperHeight = 32.0;
  static const stepperRadius = 16.0;
  static const switchWidth = 64.0;
  static const switchHeight = 28.0;
  static const switchRadius = 13.7;
  static const tabPillWidth = 77.0;
  static const tabPillHeight = 36.0;
  static const tabPillRadius = 17.9;
  static const hitTarget = 44.0;
}
