// Measured from Apple's iOS 27 UI kit renderings. Generated by
// scripts/build_design_tokens.py -- do not hand-edit.
//
// On Android, this is Apple's palette on a platform with its own.
// Material has its own colour roles and its own switch, and users
// expect them. Use these when brand consistency across platforms is
// the deliberate goal -- not by default.

package design.applekit

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object AppleKitLight {
    val accent = Color(0xFF0088FF)
    val fillControl = Color(0x1F73737B)
    val fillTrack = Color(0x4C3C3C43)
    val green = Color(0xFF34C759)
    val label = Color(0xFF1A1A1A)
    val labelSecondary = Color(0x993C3C43)
    val labelTertiary = Color(0x4C3C3C43)
    val red = Color(0xFFFF383C)
    val surface = Color(0xFFE6E6E6)
}

object AppleKitDark {
    val accent = Color(0xFF0091FF)
    val fillControl = Color(0x3D757581)
    val fillTrack = Color(0x4CEBEBF5)
    val green = Color(0xFF30D158)
    val label = Color(0xFFF5F5F5)
    val labelSecondary = Color(0xB2EBEBF5)
    val labelTertiary = Color(0x4CEBEBF5)
    val red = Color(0xFFFF4245)
    val surface = Color(0xFF1A1A1A)
}

object AppleKitMetric {
    val stepperWidth = 46.0.dp
    val stepperHeight = 32.0.dp
    val stepperRadius = 16.0.dp
    val switchWidth = 64.0.dp
    val switchHeight = 28.0.dp
    val switchRadius = 13.7.dp
    val tabPillWidth = 77.0.dp
    val tabPillHeight = 36.0.dp
    val tabPillRadius = 17.9.dp
    val hitTarget = 44.dp
}
