// Measured from Apple's iOS 27 UI kit renderings. Generated by
// scripts/build_design_tokens.py -- do not hand-edit.
//
// On Android, this is Apple's palette on a platform with its own.
// Material has its own colour roles and its own switch, and users
// expect them. Use these when brand consistency across platforms is
// the deliberate goal -- not by default.

export const light = {
  accent: '#0088FF',
  fillControl: 'rgba(115, 115, 123, 0.122)',
  fillTrack: 'rgba(60, 60, 67, 0.298)',
  green: '#34C759',
  label: '#1A1A1A',
  labelSecondary: 'rgba(60, 60, 67, 0.6)',
  labelTertiary: 'rgba(60, 60, 67, 0.298)',
  red: '#FF383C',
  surface: '#E6E6E6',
} as const;

export const dark = {
  accent: '#0091FF',
  fillControl: 'rgba(117, 117, 129, 0.239)',
  fillTrack: 'rgba(235, 235, 245, 0.298)',
  green: '#30D158',
  label: '#F5F5F5',
  labelSecondary: 'rgba(235, 235, 245, 0.698)',
  labelTertiary: 'rgba(235, 235, 245, 0.298)',
  red: '#FF4245',
  surface: '#1A1A1A',
} as const;

export const metric = {
  stepperWidth: 46.0,
  stepperHeight: 32.0,
  stepperRadius: 16.0,
  switchWidth: 64.0,
  switchHeight: 28.0,
  switchRadius: 13.7,
  tabPillWidth: 77.0,
  tabPillHeight: 36.0,
  tabPillRadius: 17.9,
  hitTarget: 44,
} as const;
